# Generated by Django 2.2.7 on 2019-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='city',
            field=models.CharField(default='Varanasi', help_text='City', max_length=100),
            preserve_default=False,
        ),
    ]
