# Generated by Django 2.2.7 on 2019-11-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaplus', '0004_auto_20191112_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stores',
            options={},
        ),
        migrations.RemoveField(
            model_name='stores',
            name='city',
        ),
    ]
