# Generated by Django 2.2.7 on 2019-11-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaplus', '0005_auto_20191112_0604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stores',
            options={'ordering': ['city']},
        ),
        migrations.AddField(
            model_name='stores',
            name='city',
            field=models.CharField(default='Varanasi', help_text='City', max_length=100),
            preserve_default=False,
        ),
    ]
