# Generated by Django 2.2.7 on 2019-11-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaplus', '0006_auto_20191112_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='city',
            field=models.ForeignKey(help_text='City', on_delete=django.db.models.deletion.CASCADE, to='pharmaplus.City'),
        ),
    ]
